// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package w06exercise

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhysicalTimeServiceClient is the client API for PhysicalTimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhysicalTimeServiceClient interface {
	CurrentTime(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Time, error)
}

type physicalTimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhysicalTimeServiceClient(cc grpc.ClientConnInterface) PhysicalTimeServiceClient {
	return &physicalTimeServiceClient{cc}
}

func (c *physicalTimeServiceClient) CurrentTime(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*Time, error) {
	out := new(Time)
	err := c.cc.Invoke(ctx, "/w06exercise.PhysicalTimeService/currentTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhysicalTimeServiceServer is the server API for PhysicalTimeService service.
// All implementations must embed UnimplementedPhysicalTimeServiceServer
// for forward compatibility
type PhysicalTimeServiceServer interface {
	CurrentTime(context.Context, *ClientRequest) (*Time, error)
	mustEmbedUnimplementedPhysicalTimeServiceServer()
}

// UnimplementedPhysicalTimeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPhysicalTimeServiceServer struct {
}

func (UnimplementedPhysicalTimeServiceServer) CurrentTime(context.Context, *ClientRequest) (*Time, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentTime not implemented")
}
func (UnimplementedPhysicalTimeServiceServer) mustEmbedUnimplementedPhysicalTimeServiceServer() {}

// UnsafePhysicalTimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhysicalTimeServiceServer will
// result in compilation errors.
type UnsafePhysicalTimeServiceServer interface {
	mustEmbedUnimplementedPhysicalTimeServiceServer()
}

func RegisterPhysicalTimeServiceServer(s grpc.ServiceRegistrar, srv PhysicalTimeServiceServer) {
	s.RegisterService(&PhysicalTimeService_ServiceDesc, srv)
}

func _PhysicalTimeService_CurrentTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhysicalTimeServiceServer).CurrentTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/w06exercise.PhysicalTimeService/currentTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhysicalTimeServiceServer).CurrentTime(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhysicalTimeService_ServiceDesc is the grpc.ServiceDesc for PhysicalTimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhysicalTimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "w06exercise.PhysicalTimeService",
	HandlerType: (*PhysicalTimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "currentTime",
			Handler:    _PhysicalTimeService_CurrentTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/w06.proto",
}
